### ISSUE TITLE
Utilize javafx fontawesome instead of the current images

### ISSUE THREAD

**Issue by carldea** [jughyd/GitFx#12]
I noticed in your resources there are bitmapped images. You might want to look at Jen's work on using Font Awesome in JavaFX CSS. This will allow scalable icons. http://www.jensd.de/wordpress/?p=132

**Comment by rohitvvv** [comment]
Thanks for the suggestion. I will incorporate the Font Awesome icons in GitFX

**Comment by rohitvvv** [comment]
I have incorporated fontawesome fonts and removed all bitmapped fonts. 
![screen shot 2015-03-19 at 1 09 07 am](https://cloud.githubusercontent.com/assets/404288/6717703/78100436-cdd4-11e4-871d-18d37275d035.png)
