### ISSUE TITLE
Use TestFX to test GitFX 

### ISSUE THREAD

**Issue by rohitvvv** [jughyd/GitFx#15]
TestFX is a neat testing library for JavaFX applications. Need to Unit test all flows implemented.

**Comment by rohitvvv** [comment]
Added stub for GitFxAppTest and DialogBoxTest. Need to add test code to test the flow.

**Comment by athiruban** [comment]
While running tests it requires the user to click the appropriate button to make the test to pass. This has to be fully automated with no manual effort. Can this feature is possible??

**Comment by rohitvvv** [comment]
@athiruban You are right. The test body is an open TODO and needs some code writing. Please follow this forum https://groups.google.com/forum/#!forum/testfx-discuss . I have posted a new question here https://groups.google.com/forum/#!topic/testfx-discuss/cVefLEkBuRg . Please follow the post and feel free to complete the JUnit.
