### ISSUE TITLE
Need to format code

### ISSUE THREAD

**Issue by athiruban** [jughyd/GitFx#18]
The code lacks space in GitFxApp.java, GitFxController.java, GitFxGsonUtil.java and others. Need "Code Indentation"

**Comment by rohitvvv** [comment]
Not sure what you are reporting here. Can you elaborate? Is it the out of memory issues you are trying to indicate here?

**Comment by athiruban** [comment]
I mean to say that we need "Code Indentation". Sorry for the confusion.

**Comment by rohitvvv** [comment]
Please go ahead, fix it and raise a pull request.
