### ISSUE TITLE
Change Resource Bundle from class to ResourceBundle property file

### ISSUE THREAD

**Issue by rajmahendra** [jughyd/GitFx#31]

**Comment by rohitvvv** [comment]
Example on how to do this https://docs.oracle.com/javase/tutorial/i18n/resbundle/examples/PropertiesDemo.java
This file needs modification https://github.com/jughyd/GitFx/blob/master/src/main/java/io/github/gitfx/GitResourceBundle.java

**Comment by rohitvvv** [comment]
https://docs.oracle.com/javase/tutorial/i18n/
