### ISSUE TITLE
UI Issue: Toolbar Width

### ISSUE THREAD

**Issue by ghost** [jughyd/GitFx#47]
The toolbar is not anchored to the main parent. It should be anchored left: 0, top: 0, right: 0. This will allow the main stage to be resized as much as required and the toolbar will resize with the stage.

This is the error in the layout:
![screenshot from 2015-07-27 04 01 38](https://cloud.githubusercontent.com/assets/3393915/8897873/368d0d32-3414-11e5-934a-dd1247eabc7a.png)

To fix, the ToolBar FXML should have these properties.
AnchorPane.leftAnchor="0.0" AnchorPane.rightAnchor="0.0" AnchorPane.topAnchor="0.0"
These can be added manually or done at the top of the Properties accordion in Scene Builder.

Thanks.

**Comment by rohitvvv** [comment]
This is fixed now.
